version: '3.4'

services: 
    mongodb.poc:
        build: 
            context: .
            dockerfile: MongoDB_POC.API/Dockerfile
        container_name: mongodb.poc
        ports:
            - "5000:80"
        depends_on: 
            - mongo
    mongo:
        image: mongo
        restart: always
        container_name: mongo
        volumes:
            - ./MongoDbDocker:/var/opt/mongo
        ports:
            - 27017:27017