version: '3.1'

volumes:

    mongo_data:
        driver: local

services:

  mongo:
    image: mongo
    volumes:
      - Mongo:/var/opt/mongo
    restart: always
    ports:
      - 27017:27017
volumes:
    Mongo: